# Generated by Django 5.1 on 2024-08-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_topic', models.CharField(max_length=255)),
                ('topic_content', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('examinable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('recommended_prerequisites', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('term', models.CharField(max_length=20)),
                ('lecturer', models.CharField(max_length=100)),
                ('assessments', models.TextField(blank=True, null=True)),
                ('learning_outcome', models.TextField(blank=True, null=True)),
                ('module_preparation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
