# Generated by Django 5.1 on 2024-08-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_code_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='programming',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
