# Generated by Django 5.1 on 2024-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='module_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='keywords',
        ),
        migrations.AlterModelTable(
            name='module',
            table='info',
        ),
    ]
